# Generated by Django 2.2 on 2020-09-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(max_length=2)),
                ('mostcommonname', models.CharField(max_length=50)),
                ('scientificname', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('commonname1', models.CharField(blank=True, max_length=100, null=True)),
                ('commonname2', models.CharField(blank=True, max_length=100, null=True)),
                ('commonname3', models.CharField(blank=True, max_length=100, null=True)),
                ('commonname4', models.CharField(blank=True, max_length=100, null=True)),
                ('leaves1', models.CharField(blank=True, max_length=100, null=True)),
                ('leaves2', models.CharField(blank=True, max_length=100, null=True)),
                ('leaves3', models.CharField(blank=True, max_length=100, null=True)),
                ('leaves4', models.CharField(blank=True, max_length=100, null=True)),
                ('fruits1', models.CharField(blank=True, max_length=100, null=True)),
                ('fruits2', models.CharField(blank=True, max_length=100, null=True)),
                ('fruits3', models.CharField(blank=True, max_length=100, null=True)),
                ('fruits4', models.CharField(blank=True, max_length=100, null=True)),
                ('link1', models.CharField(blank=True, max_length=100, null=True)),
                ('link2', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('Map', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
