# Generated by Django 2.2 on 2020-09-16 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='type',
            new_name='typetree',
        ),
    ]
