# Generated by Django 2.2 on 2020-09-16 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20200916_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='commonname1',
            new_name='CommonName1',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='commonname2',
            new_name='CommonName2',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='commonname3',
            new_name='CommonName3',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='commonname4',
            new_name='CommonName4',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='fruits1',
            new_name='Fruits1',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='fruits2',
            new_name='Fruits2',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='fruits3',
            new_name='Fruits3',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='fruits4',
            new_name='Fruits4',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='initial',
            new_name='Initial',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='leaves1',
            new_name='Leaves1',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='leaves2',
            new_name='Leaves2',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='leaves3',
            new_name='Leaves3',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='leaves4',
            new_name='Leaves4',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='link1',
            new_name='Link1',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='link2',
            new_name='Link2',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='mostcommonname',
            new_name='MostCommonName',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='scientificname',
            new_name='ScientificName',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='typetree',
            new_name='Type',
        ),
    ]
