# Generated by Django 2.2 on 2020-09-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_auto_20200916_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('initial', models.TextField(blank=True, db_column='Initial', null=True)),
                ('mostcommonname', models.TextField(blank=True, db_column='MostCommonName', null=True)),
                ('scientificname', models.TextField(blank=True, db_column='ScientificName', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('commonname1', models.TextField(blank=True, db_column='CommonName1', null=True)),
                ('commonname2', models.TextField(blank=True, db_column='CommonName2', null=True)),
                ('commonname3', models.TextField(blank=True, db_column='CommonName3', null=True)),
                ('commonname4', models.TextField(blank=True, db_column='CommonName4', null=True)),
                ('leaves1', models.TextField(blank=True, db_column='Leaves1', null=True)),
                ('leaves2', models.TextField(blank=True, db_column='Leaves2', null=True)),
                ('leaves3', models.TextField(blank=True, db_column='Leaves3', null=True)),
                ('leaves4', models.TextField(blank=True, db_column='Leaves4', null=True)),
                ('bark1', models.TextField(blank=True, db_column='Bark1', null=True)),
                ('bark2', models.TextField(blank=True, db_column='Bark2', null=True)),
                ('bark3', models.TextField(blank=True, db_column='Bark3', null=True)),
                ('bark4', models.TextField(blank=True, db_column='Bark4', null=True)),
                ('flowers1', models.TextField(blank=True, db_column='Flowers1', null=True)),
                ('flowers2', models.TextField(blank=True, db_column='Flowers2', null=True)),
                ('flowers3', models.TextField(blank=True, db_column='Flowers3', null=True)),
                ('flowers4', models.TextField(blank=True, db_column='Flowers4', null=True)),
                ('fruits1', models.TextField(blank=True, db_column='Fruits1', null=True)),
                ('fruits2', models.TextField(blank=True, db_column='Fruits2', null=True)),
                ('fruits3', models.TextField(blank=True, db_column='Fruits3', null=True)),
                ('fruits4', models.TextField(blank=True, db_column='Fruits4', null=True)),
                ('link1', models.TextField(blank=True, db_column='Link1', null=True)),
                ('link2', models.TextField(blank=True, db_column='Link2', null=True)),
                ('location', models.TextField(blank=True, db_column='Location', null=True)),
                ('map', models.TextField(blank=True, db_column='Map', null=True)),
            ],
            options={
                'db_table': 'Data',
            },
        ),
        migrations.DeleteModel(
            name='Tree',
        ),
    ]
